# Generated by Django 4.1.3 on 2022-11-13 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutorials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('about_us', models.TextField(blank=True)),
                ('what_we_do', models.TextField(blank=True)),
                ('contact', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('math', 'Math'), ('med', 'Medical'), ('chem', 'Chemistry'), ('def', 'Default')], default='def', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('un', 'Unspecified'), ('mem', 'Member'), ('mod', 'Moderator'), ('cr', 'Creator')], default='un', max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_groups.researchgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroupGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorial')),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_groups.researchgroup')),
            ],
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='guides',
            field=models.ManyToManyField(through='research_groups.ResearchGroupGuide', to='tutorials.tutorial'),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='members',
            field=models.ManyToManyField(through='research_groups.ResearchGroupUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
