# Generated by Django 4.1.3 on 2022-11-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_groups", "0002_researchgrouppost_researchgrouppostcomment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchgroup",
            name="description",
        ),
    ]
