# Generated by Django 4.1.3 on 2022-11-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_groups", "0003_remove_researchgroup_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="researchgrouppostcomment",
            old_name="test",
            new_name="text",
        ),
    ]
