# Generated by Django 4.1.3 on 2022-11-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_groups", "0006_alter_researchgroup_about_us_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchgroup",
            name="name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
