# Generated by Django 4.1.3 on 2022-11-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_groups", "0005_researchgroup_group_owner_and_more"),
        ("research_groups", "0007_alter_researchgroup_name"),
    ]

    operations = []
