# Generated by Django 4.1.4 on 2022-12-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_groups", "0009_alter_researchgroup_category"),
        ("research_groups", "0009_rename_project_researchgroupdisk_research_group_and_more"),
    ]

    operations = []
