# Generated by Django 4.1.3 on 2022-12-11 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("research_groups", "0010_merge_20221210_1911"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchgroupdisk",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
