# Generated by Django 4.1.3 on 2022-12-11 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("research_groups", "0011_researchgroupdisk_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchgroupdisk",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
