# Generated by Django 4.1.3 on 2022-12-11 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("research_groups", "0012_alter_researchgroupdisk_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchgrouplink",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
