# Generated by Django 4.1.4 on 2022-12-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_groups", "0013_researchgrouplink_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchgroupdisk",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="researchgrouplink",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
