# Generated by Django 4.1.4 on 2022-12-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_groups", "0010_rename_project_researchgroupdisk_research_group_and_more"),
        ("research_groups", "0015_alter_researchgroupguide_guide"),
    ]

    operations = []
