# Generated by Django 4.1.4 on 2022-12-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_groups", "0016_merge_20221217_1208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchgrouppost",
            name="added",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="researchgrouppost",
            name="edited",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="researchgrouppost",
            name="title",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
