# Generated by Django 4.1.4 on 2022-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_groups", "0017_alter_researchgrouppost_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchgrouppost",
            name="title",
            field=models.CharField(max_length=120),
        ),
    ]
