version: "1"

services:
  backend:
    restart: always
    container_name: backend
    command: "poetry run python3 ./manage.py runserver 0.0.0.0:8000"
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "backend"
      POSTGRES_PASSWORD: "pleasechangeme"
      POSTGRES_USER: "admin"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "80:80"

volumes:
  db-data:
