# Generated by Django 4.1.3 on 2022-11-13 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tutorials", "0001_initial"),
        ("research_groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("added", models.DateTimeField(auto_now_add=True)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tutorials.tutorial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("deadline", models.DateField(null=True)),
                ("funds", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "category",
                    models.CharField(
                        choices=[("def", "Default")], default="def", max_length=20
                    ),
                ),
                (
                    "guides",
                    models.ManyToManyField(
                        through="projects.GuideProject", to="tutorials.tutorial"
                    ),
                ),
                (
                    "research_groups",
                    models.ManyToManyField(to="research_groups.researchgroup"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("un", "Unspecified"),
                            ("mem", "Member"),
                            ("mod", "Moderator"),
                            ("own", "Owner"),
                        ],
                        default="un",
                        max_length=20,
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                ("edited", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="guideproject",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
    ]
