# Generated by Django 4.1.3 on 2022-11-28 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0003_rename_test_projectpostcomment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                through="projects.ProjectUser", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="role",
            field=models.CharField(
                choices=[("mem", "Member"), ("mod", "Moderator"), ("own", "Owner")],
                default="mem",
                max_length=20,
            ),
        ),
    ]
