# Generated by Django 4.1.3 on 2022-11-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_members"),
        ("projects", "0004_project_members_alter_projectuser_role"),
    ]

    operations = []
