# Generated by Django 4.1.3 on 2022-12-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_groups", "0008_merge_20221128_2007"),
        ("projects", "0005_merge_20221128_2007"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="funds",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="project",
            name="research_groups",
            field=models.ManyToManyField(blank=True, to="research_groups.researchgroup"),
        ),
    ]
