# Generated by Django 4.1.3 on 2022-12-02 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0006_alter_project_deadline_alter_project_funds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
