# Generated by Django 4.1.3 on 2022-12-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_project_project_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="funds",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
