# Generated by Django 4.1.4 on 2022-12-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_projectdisk_users_projectlink_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdisk",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="projectlink",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
