# Generated by Django 4.1.3 on 2022-12-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[("math", "Matematyka"), ("med", "Medycyna"), ("chem", "Chemia"), ("def", "Default")],
                default="def",
                max_length=20,
            ),
        ),
    ]
