# Generated by Django 4.1.4 on 2022-12-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_project_category"),
        ("projects", "0010_alter_projectdisk_name_alter_projectlink_name"),
    ]

    operations = []
