# Generated by Django 4.1.4 on 2022-12-15 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0002_tutorial_is_public"),
        ("projects", "0011_merge_20221213_2213"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guideproject",
            name="guide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="project_guide", to="tutorials.tutorial"
            ),
        ),
    ]
