# Generated by Django 4.1.4 on 2022-12-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_guideproject_guide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpost",
            name="added",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="projectpost",
            name="edited",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="projectpost",
            name="title",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
