# Generated by Django 4.1.4 on 2022-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_alter_projectpost_added_alter_projectpost_edited_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpost",
            name="title",
            field=models.CharField(max_length=120),
        ),
    ]
