# Generated by Django 4.1.4 on 2022-12-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0002_tutorial_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="type",
            field=models.CharField(
                choices=[("math", "Matematyka"), ("med", "Medycyna"), ("chem", "Chemia"), ("def", "Default")],
                default="def",
                max_length=20,
            ),
        ),
    ]
