# Generated by Django 4.1.4 on 2022-12-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0004_rename_type_tutorial_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
