# Generated by Django 4.1.3 on 2022-11-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='ann_type',
            field=models.CharField(choices=[('def', 'Default')], default='def', max_length=20),
        ),
    ]
