# Generated by Django 4.1.3 on 2022-11-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_announcement_ann_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="ann_type",
            field=models.CharField(
                choices=[
                    ("sponsor", "Poszukiwanie sponsora"),
                    ("rekrutacja", "Poszukiwanie nowych członków"),
                    ("projekt", "Poszukiwanie osób do projektu"),
                    ("def", "Default"),
                ],
                default="def",
                max_length=30,
            ),
        ),
    ]
