# Generated by Django 4.1.3 on 2022-12-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0003_alter_announcement_ann_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="edited",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
