# Generated by Django 4.1.3 on 2022-12-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0004_announcement_edited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="date",
        ),
        migrations.AddField(
            model_name="announcement",
            name="added",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="edited",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
