# Generated by Django 4.1.3 on 2022-12-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0006_alter_announcement_added_alter_announcement_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="edited",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
